appweb/blueprints/extras.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import itertools
import operator
import sys
import os.path
import functools

from flask import g, Blueprint, render_template, url_for, abort, send_file, current_app, request, redirect

extras = Blueprint("extras", __name__)

from foofind.services import plugindb

def referrer_check(fnc):
    @functools.wraps(fnc)
    def wrapped(*args, **kwargs):
        if request.referrer and request.referrer.startswith(request.url_root):
            return fnc(*args, **kwargs)
        abort(404)
    return wrapped

INFINITE = float("inf")

def category_order(data):
    if data.title.lower() == "featured":
        return -INFINITE
    return data.title

# someone's spaggheti code workaround
from foofind.blueprints.files.helpers import csrf
@extras.route("/<lang>/extras", methods=("POST",))
@csrf.exempt
def home():
    # like category without referer check
    plugins, categories = plugindb.get_plugins_with_categories()
    categories = sorted(categories.itervalues(), key=category_order)
    reqos = request.user_agent.platform # operative system for params
    return render_template('extras.html', categories=categories, page=1, reqos=reqos)

@extras.route("/<lang>/extras", defaults={"page":1, "category":None})
@extras.route("/<lang>/extras/<category>", defaults={"page":1})
@extras.route("/<lang>/extras/<category>/<int:page>")
@referrer_check
def category(category, page):
    '''
    Extras front page
    '''
    page = max(page, 1)
    if category:
        plugins = plugindb.get_plugins(category, page-1)
        categories = None
        category = plugins[0].category if plugins else plugindb.get_category(category)
    else:
        plugins, categories = plugindb.get_plugins_with_categories(page=page-1)
        categories = sorted(categories.itervalues(), key=category_order)
        category = None

    reqos = request.user_agent.platform # operative system for params
    return render_template('extras.html', categories=categories, category=category, page=page, reqos=reqos)

@extras.route("/<lang>/list", methods=("POST",))
def list():
    '''

    '''
    if "plugins" in request.form:
        plugins = plugindb.get_plugins_by_name(request.form["plugins"].split(","))
    else:
        plugins = []

    reqos = request.user_agent.platform # operative system for params
    return render_template('extras.html', plugins=plugins, reqos=reqos,
                form_plugins=request.form.get("plugins", ""),
                form_ununinstallable=request.form.get("ununinstallable", ""))

@extras.route("/<lang>/extras/info/<name>", defaults={"page":1, "category":None})
@extras.route("/<lang>/extras/<category>/<int:page>/<name>")
@referrer_check
def info(category, page, name):
    '''

    '''
    page = max(page, 1)
    plugin = plugindb.get_plugin(name)
    if plugin is None:
        abort(404)
    if category:
        category = plugindb.get_category(category)
    reqos = request.user_agent.platform # operative system for params
    return render_template('extras.html', plugin=plugin, category=category, page=page, reqos=reqos)

@extras.route("/<lang>/extras/download/<platform>/<name>")
def download(platform, name):
    path = plugindb.get_download(name, platform)
    if path:
        prefix = current_app.config["EXTRAS_DOWNLOAD_PATH"] + os.sep
        if path.startswith(prefix):
            return redirect(url_for(".download_static", path=path[len(prefix):]))
        try:
            return send_file(path)
        except:
            pass
    abort(404)

@extras.route("/static_extras/image/<name>.<image>.png")
def image(name, image):
    '''

    '''
    path = os.path.abspath(plugindb.get_image(name, image))
    if path:
        try:
            return send_file(path, mimetype="image/png")
        except:
            pass
    abort(404)

@extras.route("/static_extras/download/<path:path>")
def download_static(path):
    '''
    Static fallback (server could not be configured to serve downloads statically)
    '''
    prefix = os.path.abspath(current_app.config["EXTRAS_DOWNLOAD_PATH"]) + os.sep
    apath = os.path.normpath(prefix + path)
    if apath.startswith(prefix):
        try:
            return send_file(apath)
        except:
            pass
    abort(404)

appweb/blueprints/files.py
# -*- coding: utf-8 -*-

"""
Controladores de las páginas de búsqueda y de fichero.
"""

import json
from flask import request, render_template, g, current_app, redirect, url_for, jsonify, make_response, Blueprint
from flask.ext.wtf import Form, BooleanField, TextField, TextAreaField, SubmitField, Required, Email, Length

from base64 import b64decode
from struct import unpack

from foofind.blueprints.files import search_files
from foofind.blueprints.files.helpers import *

from foofind.services import *
from foofind.utils import logging, hex2url, url2mid
from foofind.utils.content_types import *

files = Blueprint('files', __name__)

def weight_processor(w, ct, r, nr):
    return w if w else -10

def tree_visitor(item):
    if item[0]=="_w" or item[0]=="_u":
        return None
    else:
        return item[1]["_w"]

@files.route('/<lang>', methods=["POST"])
def home():
    '''
    Renderiza la portada de la pestaña find de la aplicación.
    '''
    return render_template('index.html')

@files.route('/<lang>/search', methods=["POST"])
def search():
    '''
    Gestiona las URL de busqueda de archivos para la aplicacion.
    '''
    query=request.form.get("q",None)
    g.filetype=filetype=request.form.get("t",None)

    if query: #si no se ha buscado nada se manda al inicio
        query = query.replace("_"," ")  #para que funcionen la busqueda cuando vienen varias palabras

    filters = {"src":"torrent"}

    ori_query = query

    _in = [i for i, v in enumerate(g.categories) if v[0] == filetype]
    if filetype and _in :
        _id = _in[0]
        if "t" in g.categories[_id][1]:
            filters["type"] = g.categories[_id][1]['t']
        if "q" in g.categories[_id][1]:
            _type = g.categories[_id][1]['q']
            query = "%s (%s)" % (query, _type)

    args = filters.copy()
    args["q"] = ori_query
    if ori_query != query:
        args['type'] = _type
    g.args=args

    sure = False
    total_found=0

    if query:
        search_results = search_files(query, filters, min_results=50, last_items=[], non_group=True, order=("@weight*r", "e DESC, ok DESC, r DESC, fs DESC", "@weight*r"), weight_processor=weight_processor, tree_visitor=tree_visitor)
    else:
        search_results = {"last_items":[], "files":[], "result_number":""}

    return render_template('search.html',
        query=ori_query, filetype=filetype, last_items=search_results["last_items"],
        files=[torrents_data(afile) for afile in search_results["files"]],
        result_number=search_results["result_number"].replace(query, ori_query)
    )

@files.route('/<lang>/searcha',methods=['POST'])
def searcha():
    '''
    Responde las peticiones de busqueda por ajax
    '''

    query=request.form.get("query",None)
    g.filetype=filetype=request.form.get("filetype",None)

    if not query: #si no se ha buscado nada se manda al inicio
        logging.error("Invalid data for AJAX search request.")
        return jsonify({})

    query = query.replace("_"," ") if query is not None else None #para que funcionen la busqueda cuando vienen varias palabras
    filters = {"src":"torrent"}
    ori_query = query

    _in = [i for i, v in enumerate(g.categories) if v[0] == filetype]
    if filetype and _in:
        _id = _in[0]
        if "t" in g.categories[_id][1]:
            filters["type"] = g.categories[_id][1]['t']
        if "q" in g.categories[_id][1]:
            _type = g.categories[_id][1]['q']
            query = "%s (%s)" % (query, _type)

    args = filters.copy()
    args["q"] = ori_query
    if ori_query != query:
        args['type'] = _type
    g.args=args

    last_items = []
    try:
        last_items = b64decode(str(request.form["last_items"]) if "last_items" in request.form else "", "-_")
        if last_items:
            last_items = unpack("%dh"%(len(last_items)/2), last_items)
    except BaseException as e:
        logging.error("Error parsing last_items information from request.")

    sure = False
    total_found=0

    search_results = search_files(query, filters, min_results=0, last_items=last_items, non_group=True, order=("@weight*r", "e DESC, ok DESC, r DESC, fs DESC", "@weight*r"), weight_processor=weight_processor, tree_visitor=tree_visitor)

    response = make_response(render_template('file.html',files=[torrents_data(afile) for afile in search_results["files"]]))
    del search_results["files"]

    response.headers["X-JSON"]=json.dumps(search_results)
    return response

def torrents_data(data):
    valid_torrent = False

    if not data or not "sources" in data["view"]:
        return None, None

    data['view']["torrent_sources"] = {"magnet":None, "sources_list":[]}
    for source, item in data["view"]["sources"].iteritems():
        if source == "tmagnet":
            data['view']["torrent_sources"]["magnet"] = item["urls"][0]
            valid_torrent = True
        elif item["icon"]=="torrent":
            valid_torrent = True
            data['view']["torrent_sources"]["sources_list"].extend(item["urls"])

    # no tiene origenes validos
    if not valid_torrent:
        return None, None

    desc = None
    # organiza mejor la descripcion del fichero
    if "description" in data["view"]["md"]:

        # recupera la descripcion original
        desc = data["view"]["md"]["description"]
        del data["view"]["md"]["description"]

        # inicializa variables
        long_desc = False
        short_desc = None
        acum = []

        # recorre las lineas de la descripcion
        for line in desc.split("\n"):
            # si llega a pasar despues acumular algo, hay que mostrar la desc larga
            if acum:
                long_desc = True

            # ignora lineas con muchos caracteres repetidos
            prev_char = repeat_count = 0
            for char in line:
                if prev_char==char:
                    repeat_count+=1
                else:
                    repeat_count = 0
                if repeat_count>5:
                    line=""
                    break
                prev_char = char

            # si la linea es "corta", la toma como fin de parrafo
            if len(line)<50:
                if acum:
                    if line: acum.append(line)

                    # si el parrafo es mas largo que 110, lo usa
                    paraph = " ".join(acum)
                    acum = [] # antes de seguir reinicia el acum
                    paraph_len = len(paraph)
                    if paraph_len>90:
                        short_desc = paraph
                        if paraph_len>140: # si no es suficientemente larga sigue buscando
                            break
                    continue
            else: # si no, acumula
                acum.append(line)

        # procesa el parrafo final
        if acum:
            paraph = " ".join(acum)
            paraph_len = len(paraph)
            if paraph_len>90:
                short_desc = paraph

        # si hay descripcion corta se muestra y se decide si se debe mostrar la larga tambien
        if short_desc:
            data["view"]["md"]["short_desc"] = short_desc
            long_desc = long_desc or len(short_desc)>400
        else:
            long_desc = True

        if not long_desc and "nfo" in data["file"]["md"]:
            desc = data["file"]["md"]["nfo"]

        data["view"]["md"]["description"] = desc

    # preview
    if "torrent:thumbnail" in data["file"]["md"]:
        data["view"]["thumbnail"] = data["file"]["md"]["torrent:thumbnail"]

    # salud del torrent
    try:
        seeds = int(float(data['view']['md']['seeds'])) if 'seeds' in data['view']['md'] else 0
    except:
        seeds = 0
    try:
        leechs = int(float(data['view']['md']['leechs'])) if 'leechs' in data['view']['md'] else 0
    except:
        leechs = 0

    base_rating = int(2/(leechs+1.)) if seeds==0 else min(10,int(seeds/(leechs+1.)*5))
    data['view']['health'] = int(base_rating/2.5)
    data['view']['rating'] = base_rating/2
    data['view']['seeds'] = seeds
    data['view']['leechs'] = leechs

    return data

@files.route('/<lang>/complaint', methods=['POST'])
def complaint():
    '''
    Procesa los datos del formulario para reportar enlaces.
    '''
    try:
        form = ReportLinkForm(request.form)
        if form.validate():
            urlreported = "/download/"+form.file_id.data+"/"
            pagesdb.create_complaint(dict([("linkreported","-"),("urlreported",urlreported),("ip",request.remote_addr)]+[(field.name,field.data) for field in form]))
            response = make_response("true")
        else:
            response = make_response(repr(form.errors.keys()))
    except BaseException as e:
        logging.error("Error on file complaint.")
        response = make_response("false")

    response.mimetype = "application/json"
    return response

class ReportLinkForm(Form):
    '''
    Formulario para reportar enlaces
    '''
    name = TextField("Your name:", validators=[Required()])
    surname = TextField("Your surname:", validators=[Required()])
    company = TextField("Your company:")
    email = TextField("Your email:", validators=[Required(),Email()])
    phonenumber = TextField("Your phone number:")
    file_id = TextField("File identifier:", validators=[Required(), Length(16,16)])
    reason = TextField("Reason of your complaint:", validators=[Required()])
    message = TextAreaField("Your message:", validators=[Required()])
    accept_tos = BooleanField(validators=[Required()])
    submit = SubmitField()

appweb/templates/__init__.py
# -*- coding: utf-8 -*-
from babel.numbers import get_decimal_symbol, get_group_symbol
from math import log

from foofind.templates import number_format_filter, format_timedelta_filter, urlencode_filter, number_friendly_filter, pformat, numeric_filter, markdown_filter, seoize_filter
from foofind.utils.htmlcompress import HTMLCompress
from foofind.utils import logging

import foofind.templates
def _(x): return x
foofind.templates._ = _

def register_filters(app):
    '''
    Registra filtros de plantillas
    '''
    app.jinja_env.filters['numberformat'] = number_format_filter
    app.jinja_env.filters['format_timedelta'] = format_timedelta_filter
    app.jinja_env.filters['urlencode'] = urlencode_filter
    app.jinja_env.filters['numberfriendly'] = number_friendly_filter
    app.jinja_env.filters['pprint'] = pformat
    app.jinja_env.filters['numeric'] = numeric_filter
    app.jinja_env.filters['markdown'] = markdown_filter
    app.jinja_env.filters['seoize'] = seoize_filter
    app.jinja_env.globals["number_size_format"] = number_size_format
    app.jinja_env.add_extension(HTMLCompress)

format_cache = {}
def number_size_format(size, lang="en"):
    '''
    Formatea un tamaño de fichero en el idioma actual
    '''
    if not size:
        return None, None
    elif int(float(size))==0:
        return "0", ("B","bytes")

    if lang in format_cache:
        decimal_sep, group_sep = format_cache[lang]
    else:
        decimal_sep, group_sep = format_cache[lang] = (get_decimal_symbol(lang), get_group_symbol(lang))

    try:
        if size<1000: # no aplica para los bytes
            return str(size), ("B","bytes")
        else:
            size = log(float(size),1000)
            number = 1000**(size-int(size))

            # parte decimal
            dec_part = int((number-int(number))*100)
            dec_part = "" if dec_part==0 else decimal_sep+"0"+str(dec_part) if dec_part<10 else decimal_sep+str(dec_part)

            # genera salida
            return ''.join(
                reversed([c + group_sep if i != 0 and i % 3 == 0 else c for i, c in enumerate(reversed(str(int(number))))])
            ) + dec_part, (("KB","kilobytes"),("MB","megabytes"),("GB","gigabytes"),("TB","terabytes"))[int(size)-1]
    except BaseException as e:
        logging.exception(e)
        return None, None

appweb/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>App - FIND</title>
    {% if g.wakalaka %}
        <link rel="stylesheet" type="text/css" href="http://test.wakalaka.es/{{g.license_name}}/appweb/static/{{g.license_name}}/css/{{g.license_name}}.css"/>
    {% else %}
        {%- assets "css_" + g.license_name -%}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
        {%- endassets -%}
    {% endif %}
    {{ g.analytics_code|safe }}
    {%- assets "js_appweb" -%}
        <script src="{{ ASSET_URL }}"></script>
    {%- endassets -%}
    <![if !IE]>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'>
    <![endif]>
    {% block head %}{% endblock %}
</head>
<body>
<div id="app">
    {%- block content %}{%- endblock %}
</div><!--end of #app-->
</body>
</html>

appweb/templates/extras.html
{% extends "base.html" %}

{% macro render_installbutton(plugin, action="download") %}
<a class="installbutton button" id="plugin:{{plugin.name}}"
    {%- if action != "download" %}
    data-action="{{action}}"
    {%- endif %}
    {%- if plugin.checksum %}
    data-checksum="{{plugin.checksum}}"
    {%- endif %}
    {%- if plugin.minversion %}
    data-minversion="{{plugin.minversion}}"
    {%- endif %}
    href="action:download({{plugin.get_download_json(reqos)}})"></a>
{% endmacro %}

{% macro render_plugins(category, in_category=False) %}
{% if category.plugins %}
<ul class="plugincards">
{% for plugin in category.plugins %}
    <li>
        <a class="plugincard" href="{{
            url_for('extras.info', lang=g.lang, category=category.name, name=plugin.name, page=page)
            if in_category else
            url_for('extras.info', lang=g.lang, name=plugin.name, page=page)
            }}" title="More...">
            <h3>{{plugin.title|capitalize}}</h3>
            <p>{{plugin.summary}}</p>
        </a>
        {{ render_installbutton(plugin) }}
    </li>
{% endfor %}
</ul>
<span class="clearer"></span>
{% endif %}
{% endmacro %}

{% macro render_plugin_list(plugins) %}
<ul>
{% for plugin in plugins %}
    <li class="result-item just-added result-plugin result-{{ 'even' if loop.index is divisibleby(2) else 'odd' }}">
        <div class="wrap-result">
            <div class="result-main-data">
                <div class="wrap-result-title">
                    <div class="result-title-info">
                        <div class="result-title" title="{{ plugin.title }}">
                            <p class="result-title">
                                <span>{{ plugin.title }}</span>
                            </p>
                        </div>
                    </div>
                    <div class="result-info">
                        <ul class="result-info">
                            <li class="sele-summary">
                                <span>{{ plugin.summary }}</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="result-more-info">
                    <div class="result-more-info-text">
                        <p>{{ plugin.description|markdown }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="result-actions">
            <ul class="result-actions">
                <li class="result-action-download">
                    {{ render_installbutton(plugin, 'uninstall') }}
                </li>
                <li class="result-action-info">
                    <a class="button button-off">
                        <span>
                            {{- "" -}}<img src="{{g.static_prefix}}/{{g.license_name}}/imgs/ico.button-18-info-off.png">
                            {{- "" -}}<img src="{{g.static_prefix}}/{{g.license_name}}/imgs/ico.button-18-info-on.png">
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </li>
{% endfor %}
</ul>
{% endmacro %}

{% block head %}
<script type="text/javascript">
(function(){
    // Global variables
    var ununinstallable = $A(), // updated on dom:ready
        clickable_states = ["uninstall",  "install", "update", "failed", "downloading"];
    // Public JS interface
    window.update_plugin_state=function(data){
        // Update plugin data of current page according to given client state
        var c="", t="", a="", d="", n, p = 0,
            actions = ["action:download", "action:uninstall"];
        for(var name in data){
            n = $("plugin:" + name);
            if(n===null) continue;
            switch(parseInt(data[name])){
                case -4:
                    // Installed, but server version is incompatible
                    if(n.readAttribute("data-action")=="uninstall"){
                        c = "state_uninstall";
                        t = "uninstall";
                        a = "action:uninstall";
                        d = "Uninstall this plugin";
                        }
                    else{
                        c = "state_non_compatible";
                        t = "non updateable";
                        a = "action:download";
                        d = "Plugin update is not compatible with current program version";
                        }
                    break;
                case -3:
                    // Server version is incompatible
                    c = "state_non_compatible";
                    t = "uncompatible";
                    a = "action:download";
                    d = "Plugin not compatible with current program version";
                    break;
                case -2:
                    // Download or install failed
                    c = "state_failed";
                    t = "failed";
                    a = "action:download";
                    d = "Install failed, click for retry";
                    break;
                case -1:
                    // Server version is different than installed version
                    c = "state_update";
                    if(n.readAttribute("data-action")=="uninstall")
                        t = "outdated";
                    else
                        t = "update";
                    a = "action:download";
                    d = "Click to install an updated version of this plugin";
                    break;
                case 0:
                    // Server version is available
                    c = "state_install";
                    if(n.readAttribute("data-action")=="uninstall")
                        t = "reinstall";
                    else
                        t = "install";
                    a = "action:download";
                    d = "Click to install this plugin";
                    break;
                case 1:
                    // Downloading and installing
                    p = Math.round((data[name]-1)*100); // Progress
                    c = "state_downloading";
                    t = "downloading ( " + p + "% )";
                    a = "action:uninstall";
                    d = "This plugin is being downloaded. Click to cancel.";
                    break;
                case 2:
                    // Installed but not initialized
                case 3:
                    // Installed
                default:
                    if(n.readAttribute("data-action")=="uninstall"){
                        if(ununinstallable.indexOf(name)==-1){
                            c = "state_uninstall";
                            t = "uninstall";
                            d = "Uninstall this plugin";
                            }
                        else{
                            c = "state_non_compatible";
                            t = "internal";
                            d = "This plugin cannot be uninstalled";
                            }
                        a = "action:uninstall";
                        }
                    else{
                        c = "state_installed";
                        t = "installed";
                        a = "action:download";
                        d = "Plugin already installed";
                        }
                }
            // Update old action with new action
            for(var i=0,l=actions.length;i<l;i++)
                if(n.href.substr(0, actions[i].length)==actions[i]){
                    if(actions[i] != a)
                        n.href = a + n.href.substr(actions[i].length);
                    break;
                    }
            // Update class
            n.className = "installbutton " + c;
            n.update(t); // Update text
            n.title = d; // Update tooltip
            }
        // Update numinstalled
        if($("numinstalled"))
            $("numinstalled").update(
                $$(".installbutton").length
                    - $$(".installbutton.state_install").length
                    - $$(".installbutton.state_downloading").length
                    );
        };
    window.update_plugin_list=function(data){
        // Show information about plugins for given client data
        var form=$("plugin_list_form"), pluginlist="", ununinstallablelist="";
        for(var i=0,l=data.length;i<l;i++){
            pluginlist += "," + data[i].name;
            if(!data[i].uninstallable) ununinstallablelist += "," + data[i].name;
            };
        form.plugins.value = pluginlist.substr(1);
        form.ununinstallable.value = ununinstallablelist.substr(1);
        form.submit();
        };
    // dom:ready initialization
    document.observe("dom:loaded", function(){
        // Initialize events and call 'state' action with current shown plugins
        var elements, elm, data, r=[],
            valid_int_data=["checksum"],
            valid_str_data=["minversion", "action"],
            info_cback = function(){
                var item=this.up(".result-item");
                this.className=item.hasClassName("result-expanded")?"button button-off":"button button-on";
                item.toggleClassName("result-expanded");
                },
            cback = function(e){
                // Block non-clickable states
                for(var i=0,l=clickable_states.length;i<l;i++)
                    if(this.hasClassName("state_" + clickable_states[i]))
                        return true;
                e.stop();
                };
        // Update ununinstallablelist plugin list
        ununinstallable = $A($("plugin_list_form").ununinstallable.value.split(","));
        // Create shown plugin data array and attach click restriction events
        elements=$$(".installbutton");
        for(var i=0,l=elements.length;i<l;i++){
            elm = elements[i];
            data = {name: elm.id.substr(7)};

            // Numeric data properties
            for(var j=0,k=valid_int_data.length;j<k;j++)
                if(elm.hasAttribute("data-" + valid_int_data[j]))
                    data[valid_int_data[j]] = parseInt(elm.readAttribute("data-checksum"));

            // String data properties
            for(var j=0,k=valid_str_data.length;j<k;j++)
                if(elm.hasAttribute("data-" + valid_str_data[j]))
                    data[valid_str_data[j]] = elm.readAttribute("data-checksum");

            r[r.length] = data;
            elm.observe("click", cback);
            }
        // Attach info button
        elements=$$(".result-action-info .button");
        for(var i=0,l=elements.length;i<l;i++){
            elm = elements[i];
            elm.observe("click", info_cback);
            }
        // Send plugin data to client using action:state(JSON)
        document.location.href = "action:state(" + Object.toJSON(r) + ")";
        });
    }());
</script>
{% endblock %}

{% block content %}
<form id="plugin_list_form" method="post" class="hiddenform" action="{{url_for('extras.list', lang=g.lang)}}">
{%- if g.version_code %}<input type="hidden" name="version" value="{{g.version_code}}">{%- endif %}
<input type="hidden" name="_csrf_token" value="{{ csrf_token() }}"/>
<input type="hidden" name="plugins" value="{{ form_plugins if form_plugins is defined else ''}}"/>
<input type="hidden" name="ununinstallable" value="{{ form_ununinstallable if form_ununinstallable is defined else ''}}"/>
</form>
<div id="infotasks">
    {% if plugin %}
    <p class="title">{{plugin.title|capitalize}}</p>
    <p class="goback"><a href="{{
        url_for('extras.category', lang=g.lang, page=page, category=category.name)
        if category else
        url_for('extras.category', lang=g.lang, page=page)
        }}">Go back</a></p>
    {% elif plugins is defined %}
    <p class="title"><span id="numinstalled">{{ plugins|length }}</span> installed plugins</p>
    <p class="goback"><a href="{{url_for('extras.category', lang=g.lang)}}">Go back</a></p>
    {% elif category %}
    <p class="title">{{category.title|capitalize}}</p>
    <p class="goback"><a href="{{url_for('extras.category', lang=g.lang)}}">Go back</a></p>
    {% else %}
    <p class="title">Categories</p>
    <p class="goback"><a href="action:list()">My installed plugins</a></p>
    {% endif %}
</div>
<div id="content">
    {% if plugin %}
    <div class="plugin">
        {% if plugin.images %}
        <div class="images">
            {% for image, alt in plugin.images %}
                <img src="{{url_for('extras.image', lang=g.lang, name=plugin.name, image=image)}}" alt="{{alt}}"/>
            {% endfor %}
        </div>
        {% endif %}
        <div class="author">Uploaded by: <strong>{{ plugin.user }}</strong></div>
        <div class="description">{{ plugin.description|markdown }}</div>
        <div class="download">{{ render_installbutton(plugin) }}</div>
    </div>
    {% elif plugins %}
        {{ render_plugin_list(plugins) }}
    {% elif category %}
        {{ render_plugins(category, True) }}
        {% if page > 1 %}
        <a href="{{url_for('extras.category', lang=g.lang, category=category.name, page=page-1)}}">previous</a>
        {% endif %}
        {% for p in range(1, page, 1) %}
            <a href="{{url_for('extras.category', lang=g.lang, category=category.name, page=p)}}">{{p}}</a>
        {% endfor %}
        <a href="{{url_for('extras.category', lang=g.lang, category=category.name, page=page+1)}}">next</a>
    {% elif categories %}
        {% for category in categories %}
        <h2 class="plugin_category">{{category.title|capitalize}}</h2>
        {{ render_plugins(category) }}
        <a href="{{url_for('extras.category', lang=g.lang, category=category.name, page=1)}}">More...</a>
        {% endfor %}
    {% else %}
    <p>Nothing to show</p>
    {% endif %}
</div>
{% endblock %}